name: test

on:
  push:
    branches: [ "master" ]

jobs:
  tests:
    name: Tests
    runs-on: windows-latest

    steps:
      - name: Install python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.9

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Create token file
        run: echo "${{ secrets.NOTION_API_TOKEN }}" > token

      - name: Run pytest
        run: pytest

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Results
          path: ./allure-results

  gen_tests:
    name: Generate test
    needs: tests
    runs-on: ubuntu-latest

    steps:
      - name: Download results
        uses: actions/download-artifact@v4
        with:
          name: Results
          path: ./allure-results

      - name: Delete results
        uses: geekyeggo/delete-artifact@v5
        with:
          name: Results

      - name: Allure report
        uses: esemi/action-allure-report@v0.2.0

      - name: Upload results
        uses: actions/upload-artifact@v4.3.3
        with:
          name: allure-report
          path: ./allure-report
          overwrite: true